!16-termékadatok-lokalizációja
flowacademyhu/iota-vajdasag-brand pull request #134
Opened 2021-03-03 21:25 UTC by pakaikarolina

2021-03-03 22:35 UTC, borosr commented
Szándékosan nem a master-be akarod küldeni a pr-t?

2021-03-04 06:26 UTC, ImreTheFifth requested changes
Ez a BE és FE része is? Ha igen linkeld a másik issuet is és add hozzá a BE labelt pls. 
+Robi fenti kérdése

2021-03-04 07:04 UTC, pakaikarolina commented
> Szándékosan nem a master-be akarod küldeni a pr-t?

Szándékosan, mert a 13as branchből hoztam létre ezt, mivel amivel én dolgoztam, azok még nincsenek masteren, és hogy haladjak vele
Ez még csak a frontend része, kulön PR lesz majd a backend-re

2021-03-04 12:08 UTC, ImreTheFifth approved these changes

2021-03-04 18:24 UTC, SiposGergo commented on frontend/src/components/AddAndEditProductForm.js
> +            className="form-select "
Felesleges szóköz :)

2021-03-04 18:29 UTC, SiposGergo commented on frontend/src/i18n.js
> +  i18n.language || window.localStorage.i18nextLng || ''
Üres stringgel nem jelenne meg egy input sem a nyelvesítettek közül, helyette szerintem legyen valami utolsó fallback, pl.: a böngésző nyelve

2021-03-04 18:34 UTC, SiposGergo commented
Úgy lenne szép, ha a nyelvesített három mező ki lenne rakva egy komponensbe. Persze ahhoz az kéne, hogy egy blokkban legyenek, és gondolom, nem most tervezzük újra a formot :)

2021-03-04 18:43 UTC, 6uliver commented
> Úgy lenne szép, ha a nyelvesített három mező ki lenne rakva egy komponensbe. Persze ahhoz az kéne, hogy egy blokkban legyenek, és gondolom, nem most tervezzük újra a formot :)

Nem beszéltünk össze, de én is ugyanezt mondtam :)

2021-03-04 22:31 UTC, pakaikarolina commented on frontend/src/i18n.js
> +  i18n.language || window.localStorage.i18nextLng || ''
javítva

2021-03-04 22:47 UTC, pakaikarolina commented on frontend/src/components/AddAndEditProductForm.js
> +            className="form-select "
javítva

2021-03-05 07:50 UTC, borosr approved these changes

2021-03-05 09:58 UTC, taritamas89 approved these changes

2021-03-05 10:00 UTC, merged