!25-authentikacio
flowacademyhu/iota-vajdasag-brand pull request #42
Opened 2021-02-11 12:41 UTC by gosidominik

2021-02-11 13:55 UTC, ImreTheFifth approved these changes

2021-02-11 13:55 UTC, borosr requested changes
Töltsd fel az application.yaml-t is, de az érzékeny adatokat töröld ki.

2021-02-11 13:55 UTC, borosr commented on backend/src/main/java/hu/flowacademy/vajdasagbrand/configuration/KeycloakSecurityConfig.java
> +
Ne legyen ilyen sok üres hely, elég egy sor.

2021-02-11 13:55 UTC, borosr commented on backend/src/main/java/hu/flowacademy/vajdasagbrand/controller/UserController.java
> +
Elég egy sor

2021-02-11 13:55 UTC, borosr commented on backend/src/main/java/hu/flowacademy/vajdasagbrand/dto/LoginDto.java
> +
Ne legyen üres sor

2021-02-11 13:57 UTC, ImreTheFifth requested changes
tört vmi, ha nem javítja meg a szakos mentor által írt dolog, akkor az errorra még nézz rá, pls

2021-02-11 16:08 UTC, ImreTheFifth approved these changes

2021-02-11 23:44 UTC, borosr requested changes

2021-02-11 23:44 UTC, borosr commented on backend/src/main/java/hu/flowacademy/vajdasagbrand/service/KeycloakClientService.java
> +    private Keycloak getInstance() {
Ha ez a pr csak az authentikációt valósítja meg, akkor töröld kérlek a felhasználó létrehozásra szolgáló kódrészeket.

2021-02-12 08:19 UTC, borosr approved these changes

2021-02-12 08:19 UTC, borosr commented on backend/src/main/java/hu/flowacademy/vajdasagbrand/service/KeycloakClientService.java
> +    @Value("${keycloakBackendClient.serverUrl}")
Egyelőre jó, a regisztrációs pr javítani fog a struktúrán.

2021-02-12 08:20 UTC, merged