!26-regisztráció
flowacademyhu/iota-vajdasag-brand pull request #53
Opened 2021-02-15 10:14 UTC by zterhes

2021-02-15 14:29 UTC, ImreTheFifth requested changes
Ez egy már lezárt issue-ra mutat. Ez tényleg így van és direkt? :)

2021-02-15 17:15 UTC, borosr requested changes

2021-02-15 17:15 UTC, borosr commented on backend/src/main/java/hu/flowacademy/vajdasagbrand/controller/UserController.java
> +        String password= userDTO.getPassword();
Nem kell külön változó.

2021-02-15 17:15 UTC, borosr commented on backend/src/main/java/hu/flowacademy/vajdasagbrand/service/KeycloakClientService.java
> +    public void createAccount(String email,String password) throws ValidationException {
Formázd meg a kódot.

2021-02-15 17:15 UTC, borosr commented on backend/src/main/java/hu/flowacademy/vajdasagbrand/service/UserService.java
> +    public User userRegistrationData(User user,String password) throws ValidationException {
Formázd meg

2021-02-15 17:15 UTC, borosr commented on backend/src/test/java/hu/flowacademy/vajdasagbrand/service/KeycloakClientServiceTest.java
> +        keycloakClientService.createAccount(email,password);
Formázd meg

2021-02-15 17:23 UTC, borosr commented
@ImreTheFifth Igen, közben kiderült, hogy megváltoztak a követelmények.

2021-02-15 17:57 UTC, ImreTheFifth approved these changes

2021-02-15 17:58 UTC, ImreTheFifth reviewed
Thx @borosr

2021-02-16 10:53 UTC, ImreTheFifth approved these changes

2021-02-16 10:59 UTC, borosr approved these changes

2021-02-16 10:59 UTC, merged