!8-cegregisztracio-jovahagyasa
flowacademyhu/iota-vajdasag-brand pull request #56
Opened 2021-02-16 12:34 UTC by ttiborgh

2021-02-16 13:15 UTC, ImreTheFifth approved these changes

2021-02-16 16:00 UTC, 6uliver commented on frontend/src/communications/userApi.js
> +    return await axios.put(`http://localhost:3000/users/${user.id}/approval`);
Elég lenne csak a userId-t átadni.

2021-02-16 16:01 UTC, 6uliver commented on frontend/src/components/listofusers/ApproveButton.js
> +  return user.isApproved ? (
Valahogy egyszerűsítsünk.

2021-02-16 16:01 UTC, 6uliver commented on frontend/src/components/listofusers/ListElement.js
> +
Töröljük.

2021-02-16 16:02 UTC, 6uliver commented on frontend/src/components/useUsers.js
> +  const sendRegistrationApproval = async (user) => {
Rakjuk useCallback-be.

2021-02-17 10:21 UTC, 6uliver commented on .github/workflows/main.yml
> -      - name: Setup GCloud
Most csináltam meg a deployt, ne szedjük ki kérlek :D

2021-02-17 10:21 UTC, 6uliver commented on .gitignore
> -backend/testDb/db.mv.db
Miért?

2021-02-17 10:21 UTC, 6uliver commented on backend/.gitignore
> -/testDb/
Miért?

2021-02-17 10:22 UTC, 6uliver commented on backend/docker-compose.yaml
> -    entrypoint: "/keycloak/entrypoint.sh"
Miért?

2021-02-17 10:22 UTC, 6uliver requested changes
Valami nagyon összekavarodott, a master-ről valamit rosszul húztál le.

2021-02-17 11:47 UTC, ImreTheFifth commented
Monster pr

2021-02-17 11:47 UTC, closed without merging