!32-termek-listazasa
flowacademyhu/iota-vajdasag-brand pull request #80
Opened 2021-02-23 13:03 UTC by ttiborgh

2021-02-23 13:59 UTC, ImreTheFifth approved these changes

2021-02-23 16:58 UTC, borosr requested changes

2021-02-23 16:58 UTC, borosr commented on backend/src/main/java/hu/flowacademy/vajdasagbrand/service/ItemService.java
> +                    .map(item -> new SuperAdminItemDTO(item.getAddress(), item.getCity(),
Szervezd ki külön függvénybe a SuperAdminItemDTO generálást és itt csak method reference-t használj

2021-02-23 16:58 UTC, borosr commented on backend/src/main/java/hu/flowacademy/vajdasagbrand/service/ItemService.java
> +                    .map(item -> new CegAdminItemDTO(item.getAddress(), item.getCity(),
Szervezd ki külön függvénybe a CegAdminItemDTO generálást és itt csak method reference-t használj

2021-02-23 16:58 UTC, borosr commented on backend/src/main/java/hu/flowacademy/vajdasagbrand/service/ItemService.java
> +        if (roles.contains("ROLE_SuperAdmin")) {
A vizsgált szerepköröket szervezd ki konstansba.

2021-02-23 21:38 UTC, ttiborgh commented on backend/src/main/java/hu/flowacademy/vajdasagbrand/service/ItemService.java
> +                    .map(item -> new SuperAdminItemDTO(item.getAddress(), item.getCity(),
Kiszervezve.

2021-02-23 21:38 UTC, ttiborgh commented on backend/src/main/java/hu/flowacademy/vajdasagbrand/service/ItemService.java
> +                    .map(item -> new CegAdminItemDTO(item.getAddress(), item.getCity(),
Szintúgy kiszervezve.

2021-02-23 21:38 UTC, ttiborgh commented on backend/src/main/java/hu/flowacademy/vajdasagbrand/service/ItemService.java
> +        if (roles.contains("ROLE_SuperAdmin")) {
Done.

2021-02-24 09:01 UTC, borosr requested changes

2021-02-24 09:01 UTC, borosr commented on backend/src/main/java/hu/flowacademy/vajdasagbrand/dto/SuperAdminItemDTO.java
> +    // TODO: create Owner property and add DB connection
Ne legyen todo a kódban

2021-02-24 09:01 UTC, borosr commented on backend/src/main/java/hu/flowacademy/vajdasagbrand/repository/ItemRepository.java
> +    List<Item> findAll();
Ez minek kell? Alapból van findAll a JpaRepository-ban

2021-02-24 09:30 UTC, ttiborgh commented on backend/src/main/java/hu/flowacademy/vajdasagbrand/dto/SuperAdminItemDTO.java
> +    // TODO: create Owner property and add DB connection
Töröltem.

2021-02-24 09:30 UTC, ttiborgh commented on backend/src/main/java/hu/flowacademy/vajdasagbrand/repository/ItemRepository.java
> +    List<Item> findAll();
Töröltem.

2021-02-24 09:33 UTC, zterhes approved these changes

2021-02-24 11:38 UTC, gosidominik approved these changes

2021-02-24 11:59 UTC, borosr approved these changes

2021-02-24 12:01 UTC, merged