!12-termektörlese
flowacademyhu/iota-vajdasag-brand pull request #81
Opened 2021-02-23 16:08 UTC by zterhes

A teljes bekötéshez szükség lesz a listára is, ahol a gombot el tudjuk helyezni. -> szükséges a termék ID-ja

2021-02-23 16:31 UTC, ttiborgh approved these changes

2021-02-23 18:38 UTC, SiposGergo requested changes

2021-02-23 18:38 UTC, SiposGergo commented on frontend/src/communications/mockForUserApi.js
> +mock.onDelete('/products/2').reply(201)
Törléskor a 201, Created státuszt nem igazán tudom értelmezni.
A 200 OK, a 204 lenne mégjobb, amikor nincs konkrét adat a válaszban

2021-02-23 18:38 UTC, SiposGergo commented on frontend/src/components/Main.js
> +                <Route path="/testComponents">
valami jobb útvonal név esetleg?

2021-02-23 18:38 UTC, SiposGergo commented on frontend/src/components/listofproducts/DeleteProductButton.js
> +  //const { fetchProducts } = useProducts() fejlesztés alatt áll
Akkor vegyük ki a kommentet légyszi.

2021-02-23 18:38 UTC, SiposGergo commented on frontend/src/components/listofusers/DeleteModalButton.js
> +import DeletionResponsedModal from './DeletionResponseModal'
Egységesítsük az elnevezést, vagy DeletionResponse**d**Modal vagy d nélkül, mint a fájlnév.

2021-02-23 18:38 UTC, SiposGergo commented on frontend/src/components/listofproducts/DeleteProductButton.js
> +import DeletionResponseModal from '../listofusers/DeletionResponseModal'
Ez a modal mehetne valamiféle közös mappába szerintem, ha a usernél van, de a terméknél is használod.

2021-02-23 18:38 UTC, SiposGergo commented on frontend/src/components/listofproducts/DeleteProductButton.js
> +const DeleteModalButton = ({ productId }) => {
Komponens neve eggyezzen a fájl nevével

2021-02-23 20:07 UTC, ImreTheFifth requested changes
A BE changek feltétlen kellenek ebbe a pr-be?
Linkelj issue-t, pls
A pr neve vagy teljesen hagyja el az ékezeteket, vagy legyen benne teljesen, szóköznél '-'

Köszi! :)

2021-02-24 09:19 UTC, SiposGergo approved these changes

2021-02-24 10:13 UTC, taritamas89 reviewed
A json formázás mehetett volna akár külön PR-ben is hogy ne növelje ennek a méretét.

2021-02-24 10:13 UTC, taritamas89 commented on frontend/src/components/listofproducts/DeleteProductButton.js
> +    let output
ez az output változó itt mire jó? 🤔  ha jól látom nincs használva... akkor törölhető innen is meg a végéről is

2021-02-24 10:13 UTC, taritamas89 commented on frontend/src/components/listofusers/DeleteModalButton.js
> +    let output
szintén kérdéses az output változó

2021-02-24 10:59 UTC, taritamas89 approved these changes

2021-02-24 12:18 UTC, ImreTheFifth requested changes
Old fel a conflictot, pls, aztán mehet!

2021-02-24 15:16 UTC, ImreTheFifth approved these changes

2021-02-24 15:17 UTC, merged