!7-elfelejtett-jelszo-kerese
flowacademyhu/iota-vajdasag-brand pull request #83
Opened 2021-02-24 14:59 UTC by zterhes

2021-02-24 15:53 UTC, ImreTheFifth approved these changes

2021-02-24 17:32 UTC, SiposGergo requested changes
A teljes pull requestre nézve szerintem ezzel a funkcióval kapcsolatban a "Forgotten password" elnevezést kellene inkább használni.

2021-02-24 17:32 UTC, SiposGergo commented on frontend/src/communications/mockForUserApi.js
> +  .onPost('/forgetpassword', {
Ez a végpont elnevezés kb arra utal, mintha kérnéd a backendet, hogy felejtse el a jelszót :D 
Lehetne forgotten-password

2021-02-24 17:32 UTC, SiposGergo commented on frontend/src/communications/userApi.js
> +  return api.post('/forgetpassword', value)
Hibakezelés?

2021-02-24 17:32 UTC, SiposGergo commented on frontend/src/pages/ForgetPassword.js
> +      if (error === 'no user') {
Ha no user helyett a "forgetpassword.nouser" stringet raknád a statebe, akkor lehetne 
```return error && <h1 className="text-center">{t(error)}</h1>```

2021-02-24 17:34 UTC, SiposGergo commented on frontend/src/communications/userApi.js
> +  return api.post('/forgetpassword', value)
Láttam, hogy a komponensben kezeled, de a státuszkód ellenőrzés helye inkább az apiban van szerintem. Dobj itt egy errort és a komponensben azt kapd el.

2021-02-25 11:24 UTC, SiposGergo approved these changes

2021-02-25 12:00 UTC, 6uliver commented on frontend/src/pages/ForgottenPassword.js
> +  const MyForm = ({ email, title, invalidemail, noEmail, buttontext }) => (
Ezt szervezzük ki külön file-ba.

2021-02-25 16:17 UTC, taritamas89 commented on frontend/src/communications/userApi.js
> +export const forgottenpassword = async (value) => {
ennek a neve legyen camelCase, tehát forgottenPassword

2021-02-25 16:17 UTC, taritamas89 commented on frontend/src/communications/userApi.js
> +    if (e.response.status === 404 || e.response.status === 500)
ez lehetne inkább else nem? tehát valahogy így
`if (e.response.status === 400) {
  throw new Error('no user')
} else if (e.response.status === 404 || e.response.status === 500) {
  throw new Error('no server')
} else {
  throw new Error(e) // ezzel ugye minden egyéb error is tovább van dobva...
}`

Így minden egyéb hibára ami valaha bekövetkezhet le lesz kezelve... esetleg magát az errort is tovább lehet dobni az első 2 esetben is

2021-02-25 16:17 UTC, taritamas89 commented on frontend/src/i18n/en.json
> +  "forgottenpassword": {
itt is lehet camelCase meg mindenhol ahol így van hivathozva a változóra... kivéve a path ott nem szokás így szerintem

2021-02-25 16:17 UTC, taritamas89 commented on frontend/src/i18n/en.json
> +    "forgetpassword": "Forgotten password"
forgottentPassword

2021-02-25 16:17 UTC, taritamas89 commented on frontend/src/i18n/en.json
> +
ez ide kell?

2021-02-25 16:17 UTC, taritamas89 commented on frontend/src/i18n/hu.json
> +  "forgottenpassword": {
camelCase legyen a változó neve

2021-02-25 16:17 UTC, taritamas89 commented on frontend/src/i18n/hu.json
> +    "forgetpassword": "Elfelejtett jelszó",
üres sor illetve forgottenPassword

2021-02-25 16:17 UTC, taritamas89 commented on frontend/src/pages/ForgottenPassword.js
> +      if (e.message === 'no server') setError('forgottenpassword.noserver')
az egyéb errort is kezeljétek le... ahogy írtam a forgottenpassword hívásnál

2021-02-26 10:46 UTC, 6uliver commented on frontend/src/communications/mockForUserApi.js
> +// const mock = new MockAdapter(api)
Akkor töröljük vagy ne importáljuk.

2021-02-26 10:46 UTC, 6uliver commented on frontend/src/communications/userApi.js
> +    console.log('response.data.content', response.data.content)
Töröljük.

2021-02-26 10:46 UTC, 6uliver commented on frontend/src/components/ForgottenPasswordForm.js
> +  ForgettenPasswordSchema,
Legyen kisbetűs, ez egy sima függvény, nem komponens és nem class.

2021-02-26 10:47 UTC, 6uliver commented on frontend/src/components/ForgottenPasswordForm.js
> +        ></InputField>
Ez lehet self-closing.

2021-02-26 10:48 UTC, 6uliver commented on frontend/src/pages/ForgottenPassword.js
> +const ForgettenPasswordSchema = (invalidEmail, noEmail) =>
Ez lehetne a form-on belül vagy egy külön file-ban.

2021-02-26 13:15 UTC, 6uliver commented on frontend/src/pages/ForgottenPassword.js
> +        ForgettenPasswordSchema={ForgottenPasswordShema}
Van olyan, hogy ez a form másik validálást kap? Ha nem, akkor ne propsban kapja, hanem a komponensen belül legyen egy import.

2021-02-26 14:13 UTC, 6uliver approved these changes

2021-02-26 14:29 UTC, 6uliver approved these changes

2021-02-26 14:34 UTC, 6uliver approved these changes

2021-02-26 14:37 UTC, merged